apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: na98yzuwc-python
  janus-idp.io/tekton: na98yzuwc-python
  backstage.io/kubernetes-id: na98yzuwc-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: na98yzuwc-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
